import { request } from "../index.js";

Page({
  data:{
    userId:getApp().globalData.userId,
    isSubcribed:true,
    isManager:false,
    isDisplay:false
  },

  onLoad:function(e){
    this.setData({userId:getApp().globalData.userId})
    request({
      url:"https://liveforjokes.icu/getIsOpen",
      data:{userId:this.data.userId},
    }).then(res=>{
      if(res.data.msg=="success"){
        console.log(res)
        this.setData({isSubcribed:res.data.obj})
      }
    })
    request({
      url:"https://liveforjokes.icu/getLevel",
      data:{userId:this.data.userId},
    }).then(res=>{
      if(res.data.msg=="success"){
        console.log(res)
        this.setData({isManager:res.data.obj})
      }
    })
    request({
      url:"https://liveforjokes.icu/isDisplay",
      data:{userId:this.data.userId},
    }).then(res=>{
      if(res.data.obj){
        console.log(res)
        this.setData({isDisplay:res.data.obj})
      }
    })
  },

  change:function(){
    request({
      url:"https://liveforjokes.icu/updateOpen",
      method:"POST",
      data:{userId:this.data.userId},
      header:{
        "Content-Type": "application/x-www-form-urlencoded"
      },
    }).then(res=>{
      if(res.data.msg=="success"){
        this.setData({isSubcribed:!this.data.isSubcribed})
      }
    })
  },
  changeManager:function(e){
    if(this.data.isManager){
      request({
        method:"POST",
        header:{
          "Content-Type": "application/x-www-form-urlencoded"
        },
        url:"https://liveforjokes.icu/deleteManger",
        data:{userId:this.data.userId},
      }).then(res=>{
        console.log(res);
        this.setData({isManager:false})
      })
    }
    else{
      request({
        method:"POST",
        header:{
          "Content-Type": "application/x-www-form-urlencoded"
        },
        url:"https://liveforjokes.icu/addManger",
        data:{userId:this.data.userId},
      }).then(res=>{
        console.log(res);
        this.setData({isManager:true})
      })
    }
  }
})